# Generated by Django 5.0.7 on 2024-07-15 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDatabase',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('employee_id', models.IntegerField()),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('salaryLPA', models.IntegerField()),
                ('total_experience', models.CharField(choices=[(0, 'Beginner'), (1, '1 year'), (2, '2 years'), (3, '3 years'), (4, 'more than 3 years')], max_length=30)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('Programming_language', models.CharField(max_length=50)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(default='nil', max_length=2000)),
                ('nameofEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeDbase.employeedatabase')),
            ],
        ),
        migrations.AddField(
            model_name='employeedatabase',
            name='skillset',
            field=models.ManyToManyField(to='EmployeeDbase.skillset'),
        ),
    ]
