# Generated by Django 5.0.7 on 2024-07-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedatabase',
            name='profile_img',
            field=models.ImageField(blank=True, default='employee_logo.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employeedatabase',
            name='total_experience',
            field=models.CharField(choices=[('0', 'Beginner'), ('1', '1 year'), ('2', '2 years'), ('3', '3 years'), ('4', 'more than 3 years')], max_length=30, null=True),
        ),
    ]
