# Generated by Django 5.0.7 on 2024-07-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDbase', '0003_employeedatabase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedatabase',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedatabase',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedatabase',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedatabase',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employeedatabase',
            name='salaryLPA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedatabase',
            name='skillset',
            field=models.ManyToManyField(blank=True, null=True, to='EmployeeDbase.skillset'),
        ),
        migrations.AlterField(
            model_name='employeedatabase',
            name='total_experience',
            field=models.CharField(blank=True, choices=[('0', 'Beginner'), ('1', '1 year'), ('2', '2 years'), ('3', '3 years'), ('4', 'more than 3 years')], max_length=30, null=True),
        ),
    ]
